PLUGIN_NAME=		lldap
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Light LDAP implementation for authentication
PLUGIN_DEPENDS=		nodejs
PLUGIN_MAINTAINER=	yannick.moussette@gmail.com

.include "../../Mk/plugins.mk"